<#
  civil3dfactory - headless Civil 3D driver for AI agents.
  One accoreconsole session runs every op listed in a task JSON against one drawing.

  Usage:
    civil3dfactory.ps1 -Help                                  list every op (one line each)
    civil3dfactory.ps1 -Help <op>                             contract, parameters and an example for one op
    civil3dfactory.ps1 -Dwg <file.dwg> -View outline          L1 read-only overview (outline | stats | issues | screenshot)
    civil3dfactory.ps1 -Dwg <file.dwg> -Ops list_alignments   single op without parameters
    civil3dfactory.ps1 -Dwg <file.dwg> -Ops 'view issues'     op name + mode / key=value pairs
    civil3dfactory.ps1 -Dwg <file.dwg> -Ops '[{"op":"list_surfaces"}]'
    civil3dfactory.ps1 -Dwg <file.dwg> -Task task.json -Result result.json
    civil3dfactory.ps1 -Dwg <file.dwg> -Task task.json -Resident   reuse a resident accoreconsole (skips the ~6 s cold start)

  Notes:
    - The engine DLL lives in %APPDATA%\Autodesk\ApplicationPlugins\Civil3DFactory.bundle (a trusted location,
      so NETLOAD raises no security prompt). Install it with install.ps1 (or build it with scripts\build.ps1).
    - The result is written as JSON (-Result; default: <drawing folder>\civil3dfactory.result.json) and echoed.
    - In-memory changes are never written back to the host drawing. Add a save_dwg op with an "out" path.
    - The process must be started on a real console (Start-Process -NoNewWindow); a detached background
      start from some shells leaves accoreconsole idle.
#>
[CmdletBinding()]
param(
  [string]$Dwg,
  [string]$Task,
  [string]$Ops,
  [string]$Result,
  [ValidateSet("", "outline", "stats", "issues", "screenshot")][string]$View = "",
  [string]$Out,
  [int]$TimeoutSec = 300,
  [switch]$Resident,
  [int]$IdleSec = 600,
  [switch]$Reuse,
  [switch]$Help,
  [Parameter(ValueFromRemainingArguments = $true)][string[]]$Rest
)

$ErrorActionPreference = "Stop"
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch { }
. (Join-Path $PSScriptRoot "scripts\resident-lib.ps1")
$env:C3DF_ROOT = $PSScriptRoot

# ---------------------------------------------------------------------------
# -Help : op catalog generated by the engine at run time (cached per engine build)
# ---------------------------------------------------------------------------
function Get-C3DFHelpCatalog {
  param([Parameter(Mandatory = $true)]$Acc, [Parameter(Mandatory = $true)]$Plugin)
  $nodeJson = Join-Path $PSScriptRoot "nodes\node.json"
  $sha = [System.Security.Cryptography.SHA256]::Create()
  try {
    $bytes = [System.IO.File]::ReadAllBytes($Plugin.Dll) + [System.IO.File]::ReadAllBytes($nodeJson)
    $key = -join (($sha.ComputeHash($bytes))[0..7] | ForEach-Object { $_.ToString("x2") })
  } finally { $sha.Dispose() }
  $cacheDir = Join-Path $env:LOCALAPPDATA "Civil3DFactory\help"
  [System.IO.Directory]::CreateDirectory($cacheDir) | Out-Null
  $cache = Join-Path $cacheDir "$key.json"
  if (-not (Test-Path -LiteralPath $cache)) {
    $scr = Join-Path $env:TEMP ("c3df_help_{0}.scr" -f ([guid]::NewGuid().ToString("N")))
    Set-Content -Path $scr -Encoding ascii -Value @("NETLOAD `"$($Plugin.Dll)`"", "C3DF-Ops", "QUIT", "_Y")
    $env:C3DF_RESULT = $cache
    $noise = Join-Path $env:TEMP ("c3df_help_{0}.log" -f ([guid]::NewGuid().ToString("N")))
    try {
      Write-Host "Generating the op catalog (one accoreconsole start, cached afterwards)..."
      $proc = Start-Process -FilePath $Acc.Exe -ArgumentList @("/s", "`"$scr`"", "/l", "en-US") -NoNewWindow -PassThru -RedirectStandardOutput $noise
      if (-not $proc.WaitForExit(180 * 1000)) { $proc.Kill(); throw "accoreconsole timed out while generating the op catalog." }
    } finally {
      Remove-Item $scr, $noise -ErrorAction SilentlyContinue
      $env:C3DF_RESULT = $null
    }
    if (-not (Test-Path -LiteralPath $cache)) { throw "The engine produced no op catalog (expected $cache). Is the engine installed for Civil 3D $($Acc.Year)?" }
  }
  return (Get-Content -LiteralPath $cache -Raw -Encoding UTF8 | ConvertFrom-Json)
}

function Find-C3DFExample {
  param([Parameter(Mandatory = $true)][string]$Op)
  $exDir = Join-Path $PSScriptRoot "examples"
  if (-not (Test-Path -LiteralPath $exDir)) { return $null }
  foreach ($f in Get-ChildItem -LiteralPath $exDir -Recurse -Filter *.json -File) {
    try { $t = Get-Content -LiteralPath $f.FullName -Raw -Encoding UTF8 | ConvertFrom-Json } catch { continue }
    if ($null -eq $t.ops) { continue }
    foreach ($o in $t.ops) {
      if ($o.op -eq $Op) {
        return [pscustomobject]@{ File = $f.FullName.Substring($PSScriptRoot.Length + 1); Op = $o }
      }
    }
  }
  return $null
}

function Show-C3DFHelp {
  param([string]$Op)
  $acc = Get-C3DFAcc
  $plugin = Resolve-C3DFPlugin -Generation $acc.Generation
  $catalog = Get-C3DFHelpCatalog -Acc $acc -Plugin $plugin
  $ops = @($catalog.ops | Sort-Object op)
  if (-not $Op) {
    Write-Host ("civil3dfactory engine {0} - {1} ops (* = writes the drawing, + = has a contract in nodes/node.json)" -f $plugin.Manifest.version, $ops.Count)
    Write-Host "Run: civil3dfactory.ps1 -Help <op>   for parameters, contract and an example."
    Write-Host ""
    foreach ($o in $ops) {
      $flag = "  "
      if ($o.writes_dwg) { $flag = "* " }
      if ($o.contract) { $flag = $flag.Substring(0, 1) + "+" }
      Write-Host ("{0}{1,-36} {2}" -f $flag, $o.op, $o.desc)
    }
    return
  }
  $hit = $ops | Where-Object { $_.op -eq $Op } | Select-Object -First 1
  if (-not $hit) {
    $near = @($ops | Where-Object { $_.op -like "*$Op*" } | ForEach-Object { $_.op })
    Write-Host "Unknown op '$Op'."
    if ($near.Count -gt 0) { Write-Host ("Did you mean: " + ($near -join ", ")) }
    exit 1
  }
  Write-Host ("{0}{1}" -f $hit.op, $(if ($hit.writes_dwg) { "   (writes the drawing: add save_dwg to keep the result)" } else { "   (read-only)" }))
  Write-Host ("  " + $hit.desc)
  Write-Host ""
  Write-Host "Parameters:"
  Write-Host ("  " + $hit.params)
  if ($hit.contract) {
    Write-Host ""
    Write-Host "Contract (nodes/node.json):"
    foreach ($section in "inputs", "parameters", "outputs") {
      $sec = $hit.contract.$section
      if ($null -eq $sec) { continue }
      $pairs = @($sec.PSObject.Properties | ForEach-Object { "{0}: {1}" -f $_.Name, $_.Value })
      if ($pairs.Count -gt 0) { Write-Host ("  {0,-11} {1}" -f ($section + ":"), ($pairs -join "  |  ")) }
    }
    if ($hit.contract.effect) { Write-Host ("  {0,-11} {1}" -f "effect:", $hit.contract.effect) }
  }
  $ex = Find-C3DFExample -Op $Op
  Write-Host ""
  if ($ex) {
    Write-Host ("Example ({0}):" -f $ex.File)
    Write-Host ("  " + (ConvertTo-Json -InputObject $ex.Op -Compress -Depth 8))
  } else {
    Write-Host ("Example: {{`"ops`":[{{`"op`":`"{0}`", ...}}]}}  (no example under examples/ yet)" -f $Op)
  }
}

if ($Help) {
  $target = ""
  if ($Rest -and $Rest.Count -gt 0) { $target = $Rest[0] }
  elseif ($Ops) { $target = $Ops }
  elseif ($Dwg -and $Dwg -notmatch '\.dw[gt]$') { $target = $Dwg }   # `-Help create_corridor`: the bare word lands in -Dwg (position 0)
  Show-C3DFHelp -Op $target
  return
}

# ---------------------------------------------------------------------------
# Run a task
# ---------------------------------------------------------------------------
if (-not $Dwg) { throw "Missing -Dwg <file.dwg> (or use -Help)." }
if ($View) {
  if ($Ops -or $Task) { throw "-View cannot be combined with -Ops or -Task." }
  $Ops = "view $View"
  if ($Out) { $Ops += " out=$Out" }
}

$mode = "accoreconsole"
if ($Resident) { $mode = "resident" }
$logContext = New-C3DFRunContext -Mode $mode -Dwg $Dwg -Task $Task -Result $Result

function Fail([string]$Message, [string]$Type = "ArgumentException") {
  Write-C3DFAuditEvent -Path $logContext.AuditLog -Event "host_error" -RunId $logContext.RunId -Fields @{ error = $Message; type = $Type }
  throw $Message
}

try {
  $acc = Get-C3DFAcc
  $plugin = Resolve-C3DFPlugin -Generation $acc.Generation
} catch {
  Fail $_.Exception.Message $_.Exception.GetType().Name
}
$dll = $plugin.Dll
if (-not (Test-Path -LiteralPath $Dwg)) { Fail "Drawing not found: $Dwg" "FileNotFoundException" }
$Dwg = (Resolve-Path -LiteralPath $Dwg).Path

# --- assemble the task file
$tempTask = $false
if (-not $Task) {
  if (-not $Ops) { Fail "Need -Task <task.json>, -Ops <op | json array>, or -View <mode>." }
  $Task = Join-Path $env:TEMP ("c3df_task_{0}.json" -f ([guid]::NewGuid().ToString("N")))
  Set-Content -Path $Task -Encoding utf8 -Value (ConvertTo-C3DFTaskJson -Ops $Ops)
  $tempTask = $true
}
if (-not (Test-Path -LiteralPath $Task)) { Fail "Task file not found: $Task" "FileNotFoundException" }
$Task = (Resolve-Path -LiteralPath $Task).Path
# Placeholders let the shipped examples run from any clone location:
#   {{C3DF_ROOT}} = this repository, {{DWG_DIR}} = the drawing's folder (forward slashes, no trailing slash)
#   {{STYLE_LIBRARY}} = $env:C3DF_STYLE_LIBRARY, a style-library drawing kept outside the repository (maintainers rebuilding the demo drawings)
$taskText = Get-Content -LiteralPath $Task -Raw -Encoding UTF8
if ($taskText -match '\{\{(C3DF_ROOT|DWG_DIR|STYLE_LIBRARY)\}\}') {
  $rootFs = $PSScriptRoot.Replace('\', '/')
  $dwgDirFs = (Split-Path -Parent $Dwg).Replace('\', '/')
  if ($taskText -match '\{\{STYLE_LIBRARY\}\}') {
    if (-not $env:C3DF_STYLE_LIBRARY -or -not (Test-Path -LiteralPath $env:C3DF_STYLE_LIBRARY)) {
      Fail "The task uses {{STYLE_LIBRARY}}: set C3DF_STYLE_LIBRARY to a style-library drawing (this placeholder is for rebuilding the shipped demo drawings)." "FileNotFoundException"
    }
    $taskText = $taskText -replace '\{\{STYLE_LIBRARY\}\}', ((Resolve-Path -LiteralPath $env:C3DF_STYLE_LIBRARY).Path.Replace('\', '/'))
  }
  $taskText = $taskText -replace '\{\{C3DF_ROOT\}\}', $rootFs -replace '\{\{DWG_DIR\}\}', $dwgDirFs
  $expanded = Join-Path $env:TEMP ("c3df_task_{0}.json" -f ([guid]::NewGuid().ToString("N")))
  Set-Content -Path $expanded -Encoding utf8 -Value $taskText -NoNewline
  if ($tempTask) { Remove-Item $Task -ErrorAction SilentlyContinue }
  $Task = $expanded
  $tempTask = $true
}
if (-not $Result) { $Result = Join-Path (Split-Path -Parent $Dwg) "civil3dfactory.result.json" }
$resultDir = Split-Path -Parent ([System.IO.Path]::GetFullPath($Result))
if ($resultDir) { [System.IO.Directory]::CreateDirectory($resultDir) | Out-Null }

$env:C3DF_RUN_ID = $logContext.RunId
$env:C3DF_AUDIT_LOG = $logContext.AuditLog
$env:C3DF_RUNNER = $mode
$env:C3DF_PLUGIN_VERSION = [string]$plugin.Manifest.version
$env:C3DF_PLUGIN_COMMIT = [string]$plugin.Manifest.git_short_commit
Write-C3DFAuditEvent -Path $logContext.AuditLog -Event "plugin_resolved" -RunId $logContext.RunId -Fields @{
  dll = $dll; generation = $acc.Generation; civil3d_year = $acc.Year
  plugin_version = $env:C3DF_PLUGIN_VERSION; plugin_commit = $env:C3DF_PLUGIN_COMMIT
}

# --- resident path: the task goes to an accoreconsole that already holds the drawing
if ($Resident) {
  $t0 = Get-Date
  try {
    $taskJson = Get-Content -LiteralPath $Task -Raw -Encoding UTF8
    $freshWhenDirty = (Test-C3DFPipelineTask -TaskJson $taskJson) -and (-not $Reuse)
    $resp = Invoke-C3DFResidentOps -Dwg $Dwg -TaskJson $taskJson -ResultPath $Result `
            -RunId $logContext.RunId -AuditLog $logContext.AuditLog -IdleSec $IdleSec -FreshWhenDirty:$freshWhenDirty
    $sec = [math]::Round(((Get-Date) - $t0).TotalSeconds, 2)
    $resultExists = Test-Path -LiteralPath $Result
    Write-C3DFAuditEvent -Path $logContext.AuditLog -Event "host_complete" -RunId $logContext.RunId -Fields @{
      ok = [bool]$resp.ok; runner = "resident"; cold_started = [bool]$resp.cold_started; reloaded = [bool]$resp.reloaded
      elapsed_seconds = $sec; resident_ms = $resp.ms; result_exists = $resultExists
    }
    Write-Host "`n---- ${sec}s (resident $($resp.ms) ms, cold_started=$($resp.cold_started), reloaded=$($resp.reloaded)), result: $Result ----"
    if ($resultExists) { Get-Content $Result -Encoding UTF8 } else { $resp.result | ConvertTo-Json -Depth 64 }
    if ($resp.resident.dirty) { Write-Host "! The resident holds unsaved changes (dirty=true): run save_dwg to keep them; stop discards them." }
  } catch {
    Write-C3DFAuditEvent -Path $logContext.AuditLog -Event "host_error" -RunId $logContext.RunId -Fields @{
      error = $_.Exception.Message; type = $_.Exception.GetType().Name; stack = $_.ScriptStackTrace
      elapsed_seconds = [int]((Get-Date) - $t0).TotalSeconds
    }
    throw
  } finally {
    if ($tempTask) { Remove-Item $Task -ErrorAction SilentlyContinue }
  }
  return
}

# --- cold path: one accoreconsole per run
# "_Y" after QUIT answers "Really want to discard all changes to drawing?" - the host drawing is
# dirtied by the Civil 3D regen on load. _Y = discard = never overwrite the host drawing.
$scr = Join-Path $env:TEMP ("c3df_run_{0}.scr" -f ([guid]::NewGuid().ToString("N")))
Set-Content -Path $scr -Encoding ascii -Value @("NETLOAD `"$dll`"", "C3DF-Run", "QUIT", "_Y")
$env:C3DF_TASK = $Task
$env:C3DF_RESULT = $Result

$t0 = Get-Date
try {
  # Every path argument must carry its own quotes: Start-Process joins -ArgumentList with spaces and
  # does not quote elements that contain spaces. Unquoted, accoreconsole silently opens a different file.
  $proc = Start-Process -FilePath $acc.Exe `
          -ArgumentList @("/i", "`"$Dwg`"", "/s", "`"$scr`"", "/l", "en-US") -NoNewWindow -PassThru
  if (-not $proc.WaitForExit($TimeoutSec * 1000)) {
    $proc.Kill()
    throw "accoreconsole timed out after ${TimeoutSec}s."
  }
  $proc.Refresh()
  $sec = [int]((Get-Date) - $t0).TotalSeconds
  $resultExists = Test-Path -LiteralPath $Result
  Write-C3DFAuditEvent -Path $logContext.AuditLog -Event "host_complete" -RunId $logContext.RunId -Fields @{
    ok = $resultExists; exit_code = $proc.ExitCode; elapsed_seconds = $sec; result_exists = $resultExists
  }
  Write-Host "`n---- ${sec}s, result: $Result ----"
  if ($resultExists) { Get-Content $Result -Encoding UTF8 }
  else { Write-Host "No result file was produced (the command may not have run). Check that the engine is installed for Civil 3D $($acc.Year)." }
} catch {
  Write-C3DFAuditEvent -Path $logContext.AuditLog -Event "host_error" -RunId $logContext.RunId -Fields @{
    error = $_.Exception.Message; type = $_.Exception.GetType().Name; stack = $_.ScriptStackTrace
    elapsed_seconds = [int]((Get-Date) - $t0).TotalSeconds
  }
  throw
} finally {
  Remove-Item $scr -ErrorAction SilentlyContinue
  if ($tempTask) { Remove-Item $Task -ErrorAction SilentlyContinue }
  $env:C3DF_TASK = $null
  $env:C3DF_RESULT = $null
}
