using System;
using System.Collections.Generic;
using System.Text.Json.Nodes;
using Autodesk.AutoCAD.ApplicationServices;
using Autodesk.AutoCAD.DatabaseServices;
using Civil3DFactory.Geometry;

namespace Civil3DFactory
{
    /// <summary>
    /// Node offset_cone_contours: batch inward offsets of closed boundaries to generate contours (offset cone).
    /// Algorithm core is OffsetConeCore.cs in this folder (same core as C3DF-OffsetCone/YT in products\waterbox).
    /// </summary>
    public static partial class Ops
    {
        static JsonNode RunNodeOffsetConeContours(JsonObject a, Document doc)
            => OffsetConeContours(a, doc);

        public static JsonNode OffsetConeContours(JsonObject a, Document doc)
        {
            double z1 = GetDouble(a, "target_z", double.NaN);
            if (double.IsNaN(z1)) throw new InvalidOperationException("Missing required parameter target_z (target design elevation).");
            double n = GetDouble(a, "slope_n", double.NaN);
            if (double.IsNaN(n) || n <= 0) throw new InvalidOperationException("slope_n must be greater than 0 (the n of slope 1:n).");
            double dz = GetDouble(a, "step_dz", 0.5);
            if (dz <= 0) throw new InvalidOperationException("step_dz must be greater than 0.");
            double rFillet = GetDouble(a, "fillet_r", Math.Round(2 * n * dz, 3));
            if (rFillet < 0) throw new InvalidOperationException("fillet_r must not be negative (0 = no smoothing, no rounding).");

            bool outward = GetBool(a, "outward", false);
            string outLayer = GetString(a, "out_layer", null);   // default: same layer as the source boundary
            bool clearExisting = GetBool(a, "clear_existing", true);
            string layer = GetString(a, "layer", null);
            if (!string.IsNullOrWhiteSpace(outLayer) &&
                string.Equals(outLayer, layer, StringComparison.OrdinalIgnoreCase))
                throw new InvalidOperationException("out_layer must not equal the source boundary layer, otherwise a re-run would wipe the source boundaries too.");
            JsonArray handles = a["boundaries"] as JsonArray;
            if (string.IsNullOrEmpty(layer) && (handles == null || handles.Count == 0))
                throw new InvalidOperationException("Give at least one of boundaries (handle array) or layer (layer name).");

            Database db = doc.Database;
            using (Transaction tr = db.TransactionManager.StartTransaction())
            {
                // Collect boundaries: handles first, otherwise scan the whole layer for closed LWPOLYLINEs
                var sources = new List<Polyline>();
                if (handles != null && handles.Count > 0)
                {
                    foreach (JsonNode h in handles)
                    {
                        string hs = h != null ? h.ToString() : null;
                        ObjectId id = ResolveHandle(db, hs);
                        Polyline pl = id.IsNull ? null : tr.GetObject(id, OpenMode.ForRead) as Polyline;
                        if (pl == null)
                            throw new InvalidOperationException("Handle '" + hs + "' is not a polyline or does not exist.");
                        sources.Add(pl);
                    }
                }
                else
                {
                    foreach (ObjectId id in ModelSpace(db, tr))
                    {
                        var pl = tr.GetObject(id, OpenMode.ForRead) as Polyline;
                        if (pl != null && string.Equals(pl.Layer, layer, StringComparison.OrdinalIgnoreCase))
                            sources.Add(pl);
                    }
                    if (sources.Count == 0)
                        throw new InvalidOperationException("No polylines on layer '" + layer + "'.");
                }

                var space = (BlockTableRecord)tr.GetObject(db.CurrentSpaceId, OpenMode.ForWrite);

                // Clear the rings generated by the previous run first, otherwise contours stack up run after run
                int erased = 0;
                if (clearExisting && !string.IsNullOrWhiteSpace(outLayer))
                {
                    var srcIds = new HashSet<ObjectId>();
                    foreach (Polyline s in sources) srcIds.Add(s.ObjectId);
                    foreach (ObjectId id in ModelSpace(db, tr))
                    {
                        if (srcIds.Contains(id)) continue;
                        var old = tr.GetObject(id, OpenMode.ForRead) as Polyline;
                        if (old == null) continue;
                        if (!string.Equals(old.Layer, outLayer, StringComparison.OrdinalIgnoreCase)) continue;
                        old.UpgradeOpen();
                        old.Erase();
                        erased++;
                    }
                }
                if (!string.IsNullOrWhiteSpace(outLayer))
                    PolyAreaEnsureLayer(tr, db, outLayer, (short)GetDouble(a, "out_color", 4));
                var perBoundary = new JsonArray();
                var ringHandles = new JsonArray();
                int ringsTotal = 0, collapsed = 0, skippedOpen = 0, skippedSameZ = 0;

                foreach (Polyline src in sources)
                {
                    if (!src.Closed && !OffsetConeCore.IsSnapClosed(src)) { skippedOpen++; continue; }

                    var res = OffsetConeCore.GenerateCone(src, z1, n, dz, rFillet, final =>
                    {
                        if (!string.IsNullOrWhiteSpace(outLayer)) final.Layer = outLayer;
                        space.AppendEntity(final);
                        tr.AddNewlyCreatedDBObject(final, true);
                        ringHandles.Add(final.Handle.ToString());
                    }, outward);

                    if (res.SameElevation) { skippedSameZ++; continue; }
                    if (res.Collapsed) collapsed++;
                    ringsTotal += res.Rings;

                    perBoundary.Add(new JsonObject
                    {
                        ["handle"] = src.Handle.ToString(),
                        ["z0"] = res.Z0,
                        ["reached"] = res.Reached,
                        ["rings"] = res.Rings,
                        ["stepped_rings"] = res.SteppedRings,
                        ["collapsed"] = res.Collapsed
                    });
                }

                // Assert: silent success = failure. Not a single ring means wrong parameters or boundaries; must throw instead of ok:true.
                if (ringsTotal == 0)
                    throw new InvalidOperationException(
                        "No contour rings generated (" + sources.Count + " boundaries, " + skippedOpen + " not closed"
                        + ", " + skippedSameZ + " at the same elevation as the target). Check target_z and the boundary elevations.");

                tr.Commit();

                return new JsonObject
                {
                    ["boundaries"] = sources.Count,
                    ["outward"] = outward,
                    ["out_layer"] = outLayer,
                    ["erased_previous"] = erased,
                    ["rings_total"] = ringsTotal,
                    ["collapsed"] = collapsed,
                    ["skipped_open"] = skippedOpen,
                    ["skipped_same_elevation"] = skippedSameZ,
                    ["ring_handles"] = ringHandles,
                    ["per_boundary"] = perBoundary
                };
            }
        }
    }
}
