using System.Globalization;
using System.Text;

namespace PktForge;

/// <summary>
/// Channel (dredge / ditch) subassembly parameters: flat bottom -> side slope 1:Slope1H -> optional bench
/// (BenchWidth wide, reached at BenchHeight above the bottom) -> slope 1:Slope2H up to the ground (EG_Surface).
/// When the ground is lower than BenchHeight above the bottom the bench is skipped and the first slope daylights.
/// Optional lining slab under the bottom (LiningThickness > 0 at generation time) adds a closed shape coded "Lining".
/// </summary>
internal sealed record ChannelSpec
{
    public string Name { get; init; } = "Channel";
    public double BottomHalfWidth { get; init; } = 10;
    public double Slope1H { get; init; } = 3;
    public double BenchHeight { get; init; } = 0;
    public double BenchWidth { get; init; } = 2;
    public double Slope2H { get; init; } = 3;
    public double LiningThickness { get; init; } = 0;
    public string Units { get; init; } = "m";
    public string OutDir { get; init; } = ".";
    public string Description { get; init; } =
        "Dredge channel side: flat bottom (BottomHalfWidth) at the profile elevation, side slope 1:Slope1H, " +
        "optional bench (BenchWidth) at BenchHeight above the bottom, then 1:Slope2H up to existing ground (EG_Surface). " +
        "Point codes Origin/Bottom/Toe/Hinge/BenchIn/BenchOut/Daylight plus origin/toe-side/controlpoint-side/mp-side/daylight-side; link codes Top/Datum/Bottom/Slope/Bench/Daylight/Cut plus bottom/slope-side/flat-side. Generated by PktForge.";

    public const string Usage =
        """
        Channel subassembly (flat bottom + side slope + optional bench + optional lining shape):
          PktForge channel [options]
          --name <name>              subassembly name (default Channel); writes <name>_LEFT.pkt / <name>_RIGHT.pkt
          --bottom-half-width <m>    half of the bottom width on this side (default 10)
          --slope1-h <n>             first side slope 1:n (default 3)
          --bench-height <m>         height of the bench above the bottom; 0 = no bench (default 0)
          --bench-width <m>          bench width (default 2)
          --slope2-h <n>             slope above the bench 1:n (default 3)
          --lining <m>               lining slab thickness under the bottom; > 0 adds a closed shape coded Lining (default 0)
          --units / --out / --desc   same as daylight
        """;

    public static ChannelSpec Parse(string[] args)
    {
        var spec = new ChannelSpec();
        for (int i = 1; i < args.Length; i += 2)
        {
            string key = args[i];
            if (i + 1 >= args.Length) throw new ArgumentException(key + " is missing a value");
            string val = args[i + 1];
            spec = key switch
            {
                "--name" => spec with { Name = val },
                "--bottom-half-width" => spec with { BottomHalfWidth = Num(key, val) },
                "--slope1-h" => spec with { Slope1H = Num(key, val) },
                "--bench-height" => spec with { BenchHeight = Num(key, val) },
                "--bench-width" => spec with { BenchWidth = Num(key, val) },
                "--slope2-h" => spec with { Slope2H = Num(key, val) },
                "--lining" => spec with { LiningThickness = Num(key, val) },
                "--units" => spec with { Units = val },
                "--out" => spec with { OutDir = val },
                "--desc" => spec with { Description = val },
                _ => throw new ArgumentException("Unknown option: " + key)
            };
        }
        if (spec.BottomHalfWidth <= 0) throw new ArgumentException("bottom-half-width must be positive");
        if (spec.Slope1H <= 0 || spec.Slope2H <= 0) throw new ArgumentException("slope ratios must be positive");
        if (spec.BenchHeight < 0 || spec.BenchWidth < 0 || spec.LiningThickness < 0) throw new ArgumentException("bench and lining values must not be negative");
        return spec;
    }

    private static double Num(string key, string val)
    {
        if (!double.TryParse(val, NumberStyles.Float, CultureInfo.InvariantCulture, out double d))
            throw new ArgumentException(key + " is not a number: " + val);
        return d;
    }
}

/// <summary>Writes the channel .pkt (atc parameter block + XAML flowchart), reusing the shared package plumbing.</summary>
internal static class ChannelWriter
{
    public static string Write(ChannelSpec spec, bool isLeft)
    {
        string side = isLeft ? "Left" : "Right";
        string toolName = PktWriter.SanitizeIdentifier(spec.Name) + "_" + side;
        string guid = Guid.NewGuid().ToString("N");
        int sideVal = isLeft ? 1 : 0;
        string n(double d) => PktWriter.N(d);

        var ps = new StringBuilder();
        ps.Append($"            <Side DataType=\"long\" TypeInfo=\"16\" DisplayName=\"Side\" Description=\"Side\">{sideVal}<Enum><Left DisplayName=\"Left\">1</Left><Right DisplayName=\"Right\">0</Right></Enum></Side>\n");
        ps.Append($"            <BottomHalfWidth DataType=\"double\" TypeInfo=\"16\" DisplayName=\"BottomHalfWidth\" Description=\"Half of the bottom width on this side\">{n(spec.BottomHalfWidth)}</BottomHalfWidth>\n");
        ps.Append($"            <Slope1H DataType=\"double\" TypeInfo=\"16\" DisplayName=\"Slope1H\" Description=\"First side slope 1:Slope1H (horizontal per 1 vertical)\">{n(spec.Slope1H)}</Slope1H>\n");
        ps.Append($"            <BenchHeight DataType=\"double\" TypeInfo=\"16\" DisplayName=\"BenchHeight\" Description=\"Bench height above the bottom; 0 = no bench\">{n(spec.BenchHeight)}</BenchHeight>\n");
        ps.Append($"            <BenchWidth DataType=\"double\" TypeInfo=\"16\" DisplayName=\"BenchWidth\" Description=\"Bench width\">{n(spec.BenchWidth)}</BenchWidth>\n");
        ps.Append($"            <Slope2H DataType=\"double\" TypeInfo=\"16\" DisplayName=\"Slope2H\" Description=\"Slope above the bench 1:Slope2H\">{n(spec.Slope2H)}</Slope2H>");
        if (spec.LiningThickness > 0)
            ps.Append($"\n            <LiningThickness DataType=\"double\" TypeInfo=\"16\" DisplayName=\"LiningThickness\" Description=\"Lining slab thickness under the bottom\">{n(spec.LiningThickness)}</LiningThickness>");

        string outPath = Path.Combine(spec.OutDir, spec.Name + "_" + side.ToUpperInvariant() + ".pkt");
        PktWriter.WritePackage(outPath, guid,
            ChannelXaml.Build(spec, isLeft),
            PktWriter.BuildAtcXml(toolName, PktWriter.XmlEscape(spec.Description), guid, ps.ToString(), spec.Units));
        return outPath;
    }
}

/// <summary>
/// WF4 flowchart for the channel side. Structure (mirrors the Subassembly Composer output):
///   start: P1 origin, P2 bottom edge, L1 bottom link [+ lining points/links/shape], AP1 ground probe above P2
///   D1 [ground high enough for a bench] -> P3 hinge, L2 slope, P4 bench out, L3 bench, P5 daylight, L4 slope
///   else D2 [ground above the bottom]   -> P6 daylight from P2, L5 slope
///   else nothing (ground below the bottom: no cut on this side)
/// </summary>
internal static class ChannelXaml
{
    const string Ns = """
         xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities"
         xmlns:asa="clr-namespace:Autodesk.SubassemblyComposer.API;assembly=Subassembly.API"
         xmlns:asa1="clr-namespace:Autodesk.SubassemblyComposer.API;assembly=Subassembly.WorkflowEngine"
         xmlns:asa2="clr-namespace:Autodesk.SubassemblyComposer.ActivityLibrary;assembly=Subassembly.ActivityLibrary"
         xmlns:asw="clr-namespace:Autodesk.SubassemblyComposer.WorkflowEngine;assembly=Subassembly.WorkflowEngine"
         xmlns:av="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
         xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
         xmlns:mva="clr-namespace:Microsoft.VisualBasic.Activities;assembly=System.Activities"
         xmlns:s="clr-namespace:System;assembly=mscorlib"
         xmlns:s1="clr-namespace:System;assembly=System.Core"
         xmlns:s2="clr-namespace:System;assembly=System"
         xmlns:s3="clr-namespace:System;assembly=System.Runtime.WindowsRuntime"
         xmlns:sa="clr-namespace:System.Activities;assembly=System.Activities"
         xmlns:sads="http://schemas.microsoft.com/netfx/2010/xaml/activities/debugger"
         xmlns:sap="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation"
         xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib"
         xmlns:this="clr-namespace:"
         xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        """;

    const string Common = "Geometry=\"[Geometry]\" ShowErrors=\"True\" SubassemblyErrorCenter=\"[SubassemblyErrorCenter]\" SubassemblyRunMode=\"[SubassemblyRunMode]\"";

    static int _activity;
    static readonly List<string> _refs = new();

    static string Codes(string owner, string kind, IEnumerable<string> codes)
    {
        var sb = new StringBuilder();
        sb.Append($"<{owner}.{kind}><scg:List x:TypeArguments=\"InArgument(x:String)\" Capacity=\"4\">");
        foreach (string c in codes) sb.Append($"<InArgument x:TypeArguments=\"x:String\">{c}</InArgument>");
        sb.Append($"</scg:List></{owner}.{kind}>");
        return sb.ToString();
    }

    static string PointXY(string id, string title, string from, string dx, string dy, params string[] codes)
    {
        int aid = ++_activity;
        string fromAttr = from == null ? "FromPoint=\"{x:Null}\"" : $"FromPoint=\"{from}\"";
        return $"<asa2:CreatePoint AutoLinkCodes=\"{{x:Null}}\" AutoLinkGeometryName=\"{{x:Null}}\" {fromAttr} ActivityId=\"{aid}\" ApplyAOR=\"False\" AutoLink=\"False\" DisplayName=\"{id} {title}\" {Common} PointNumber=\"{id}\" Positioning=\"DeltaXAndDeltaY\" Side=\"[Side]\">"
             + $"<asa2:CreatePoint.Arguments><InArgument x:TypeArguments=\"x:Double\" x:Key=\"DeltaX1\">{dx}</InArgument><InArgument x:TypeArguments=\"x:Double\" x:Key=\"DeltaY1\">{dy}</InArgument></asa2:CreatePoint.Arguments>"
             + Codes("asa2:CreatePoint", "PointCodes", codes) + "</asa2:CreatePoint>";
    }

    static string PointSlopeToSurface(string id, string title, string from, string slopeExpr, params string[] codes)
    {
        int aid = ++_activity;
        return $"<asa2:CreatePoint AutoLinkCodes=\"{{x:Null}}\" AutoLinkGeometryName=\"{{x:Null}}\" ActivityId=\"{aid}\" ApplyAOR=\"False\" AutoLink=\"False\" DisplayName=\"{id} {title}\" FromPoint=\"{from}\" {Common} PointNumber=\"{id}\" Positioning=\"SlopeToSurface\" Side=\"[Side]\">"
             + "<asa2:CreatePoint.Arguments>"
             + $"<InArgument x:TypeArguments=\"x:Double\" x:Key=\"Slope3\">{slopeExpr}</InArgument>"
             + "<InArgument x:TypeArguments=\"x:Boolean\" x:Key=\"ReverseSlopeDirection3\">False</InArgument>"
             + "<InArgument x:TypeArguments=\"asw:SurfaceTarget\" x:Key=\"SurfaceTarget3\">[EG_Surface]</InArgument>"
             + "<InArgument x:TypeArguments=\"x:Double\" x:Key=\"DeltaXForLayout3\">5</InArgument>"
             + "</asa2:CreatePoint.Arguments>"
             + Codes("asa2:CreatePoint", "PointCodes", codes) + "</asa2:CreatePoint>";
    }

    static string AuxOnSurface(string id, string title, string from, string dxExpr)
    {
        int aid = ++_activity;
        return $"<asa2:CreateAuxPoint AutoLinkCodes=\"{{x:Null}}\" AutoLinkGeometryName=\"{{x:Null}}\" PointCodes=\"{{x:Null}}\" ActivityId=\"{aid}\" ApplyAOR=\"False\" AutoLink=\"False\" DisplayName=\"{id} {title}\" FromPoint=\"{from}\" {Common} PointNumber=\"{id}\" Positioning=\"DeltaXOnSurface\" Side=\"[Side]\">"
             + "<asa2:CreateAuxPoint.Arguments>"
             + $"<InArgument x:TypeArguments=\"x:Double\" x:Key=\"DeltaX4\">{dxExpr}</InArgument>"
             + "<InArgument x:TypeArguments=\"asw:SurfaceTarget\" x:Key=\"SurfaceTarget4\">[EG_Surface]</InArgument>"
             + "<x:Null x:Key=\"OffsetTarget4\" />"
             + "<InArgument x:TypeArguments=\"x:Double\" x:Key=\"DeltaYForLayout4\">3</InArgument>"
             + "</asa2:CreateAuxPoint.Arguments></asa2:CreateAuxPoint>";
    }

    static string Link(string id, string title, string start, string end, params string[] codes)
    {
        int aid = ++_activity;
        return $"<asa2:CreateLink ActivityId=\"{aid}\" ApplyAOR=\"False\" DisplayName=\"{id} {title}\" EndPoint=\"{end}\" {Common} IsEnabled=\"True\" LinkNumber=\"{id}\" StartPoint=\"{start}\">"
             + Codes("asa2:CreateLink", "LinkCodes", codes) + "</asa2:CreateLink>";
    }

    static string Shape(string id, string[] links, params string[] codes)
    {
        int aid = ++_activity;
        var names = new StringBuilder();
        foreach (string l in links) names.Append($"<x:String>{l}</x:String>");
        return $"<asa2:CreateShape ActivityId=\"{aid}\" DisplayName=\"{id}\" Geometry=\"[Geometry]\" Links=\"{string.Join(",", links)}\" ShapeNumber=\"{id}\" ShowErrors=\"True\" SubassemblyErrorCenter=\"[SubassemblyErrorCenter]\" SubassemblyRunMode=\"[SubassemblyRunMode]\">"
             + $"<asa2:CreateShape.ComponentNames>{names}</asa2:CreateShape.ComponentNames>"
             + Codes("asa2:CreateShape", "ShapeCodes", codes) + "</asa2:CreateShape>";
    }

    static string Step(string name, string sequenceTitle, IEnumerable<string> activities, string next)
    {
        _refs.Add(name);
        var sb = new StringBuilder();
        sb.Append($"<FlowStep x:Name=\"{name}\"><Sequence DisplayName=\"{sequenceTitle}\">");
        foreach (string a in activities) sb.Append(a);
        sb.Append("</Sequence>");
        if (next != null) sb.Append("<FlowStep.Next>").Append(next).Append("</FlowStep.Next>");
        sb.Append("</FlowStep>");
        return sb.ToString();
    }

    static string Decision(string name, string title, string condition, string whenTrue, string whenFalse)
    {
        _refs.Add(name);
        var sb = new StringBuilder();
        sb.Append($"<FlowDecision x:Name=\"{name}\" Condition=\"{condition}\" DisplayName=\"{title}\">");
        if (whenTrue != null) sb.Append("<FlowDecision.True>").Append(whenTrue).Append("</FlowDecision.True>");
        if (whenFalse != null) sb.Append("<FlowDecision.False>").Append(whenFalse).Append("</FlowDecision.False>");
        sb.Append("</FlowDecision>");
        return sb.ToString();
    }

    static string Member(string name, string type, string description)
    {
        string desc = description == null ? "" : $"<asw:Description2Attribute Description=\"{description}\" />";
        return $"<x:Property Name=\"{name}\" Type=\"{type}\"><x:Property.Attributes><asw:EnabledFlag2Attribute EnabledFlag=\"True\" />{desc}</x:Property.Attributes></x:Property>";
    }

    public static string Build(ChannelSpec spec, bool isLeft)
    {
        lock (_refs)
        {
            _activity = 0;
            _refs.Clear();
            int sideVal = isLeft ? 1 : 0;
            string sideName = isLeft ? "Left" : "Right";
            string side = isLeft ? "left" : "right";   // lower-case side suffix for the dredging code convention (toe-left, daylight-right ...)
            string n(double d) => PktWriter.N(d);
            bool lining = spec.LiningThickness > 0;

            // --- flowchart body (built inside-out so the nested Next chain reads naturally) ---
            string branchSimple = Step("__Simple", "Slope to ground",
                new[]
                {
                    PointSlopeToSurface("P6", "Daylight", "P2", "[1.0 / Slope1H]", "Daylight", "Daylight_Cut", "daylight-" + side),
                    Link("L5", "Side slope", "P2", "P6", "Top", "Datum", "Slope", "Daylight", "Cut", "slope-" + side)
                }, null);
            string d2 = Decision("__D2", "Ground above bottom?", "[AP1.Y &gt; P2.Y]", branchSimple, null);

            string branchBench = Step("__Bench", "Bench then slope to ground",
                new[]
                {
                    PointXY("P3", "Hinge (bench in)", "P2", "[BenchHeight * Slope1H]", "[BenchHeight]", "Hinge", "BenchIn", "controlpoint-" + side),
                    Link("L2", "Lower slope", "P2", "P3", "Top", "Datum", "Slope", "Cut", "slope-" + side),
                    PointXY("P4", "Bench out", "P3", "[BenchWidth]", "0", "BenchOut", "mp-" + side),
                    Link("L3", "Bench", "P3", "P4", "Top", "Datum", "Bench", "Flat", "flat-" + side),
                    PointSlopeToSurface("P5", "Daylight", "P4", "[1.0 / Slope2H]", "Daylight", "Daylight_Cut", "daylight-" + side),
                    Link("L4", "Upper slope", "P4", "P5", "Top", "Datum", "Slope", "Daylight", "Cut", "slope-" + side)
                }, null);
            string d1 = Decision("__D1", "Deep enough for a bench?", "[BenchHeight &gt; 0 And AP1.Y - P2.Y &gt; BenchHeight]", branchBench, d2);

            var start = new List<string>
            {
                PointXY("P1", "Origin", null, "0", "0", "Origin", "origin"),
                PointXY("P2", "Bottom edge", "P1", "[BottomHalfWidth]", "0", "Bottom", "Toe", "toe-" + side),
                Link("L1", "Flat bottom", "P1", "P2", "Top", "Datum", "Bottom", "Flat", "Cut", "bottom")
            };
            if (lining)
            {
                start.Add(PointXY("P7", "Lining under origin", "P1", "0", "[-LiningThickness]", "LiningBottom"));
                start.Add(PointXY("P8", "Lining under bottom edge", "P2", "0", "[-LiningThickness]", "LiningBottom"));
                start.Add(Link("L6", "Lining inner edge", "P1", "P7", "Lining"));
                start.Add(Link("L7", "Lining bottom", "P7", "P8", "Lining", "Subbase"));
                start.Add(Link("L8", "Lining outer edge", "P8", "P2", "Lining"));
                start.Add(Shape("S1", new[] { "L1", "L8", "L7", "L6" }, "Lining"));
            }
            start.Add(AuxOnSurface("AP1", "Ground above bottom edge", "P1", "[BottomHalfWidth]"));
            string startNode = Step("__Start", "Bottom", start, d1);

            var refs = new StringBuilder();
            foreach (string r in _refs) refs.Append($"<x:Reference>{r}</x:Reference>");

            string liningMember = lining ? Member("LiningThickness", "InArgument(x:Double)", "Lining slab thickness under the bottom") : "";
            string liningDefault = lining ? $" this:Subassembly.LiningThickness=\"{n(spec.LiningThickness)}\"" : "";

            return
$$"""
<Activity mc:Ignorable="sads sap" x:Class="Subassembly" this:Subassembly.Side="[new EnumType({{sideVal}}, &quot;{{sideName}}&quot;, &quot;Side&quot;)]" this:Subassembly.BottomHalfWidth="{{n(spec.BottomHalfWidth)}}" this:Subassembly.Slope1H="{{n(spec.Slope1H)}}" this:Subassembly.BenchHeight="{{n(spec.BenchHeight)}}" this:Subassembly.BenchWidth="{{n(spec.BenchWidth)}}" this:Subassembly.Slope2H="{{n(spec.Slope2H)}}"{{liningDefault}} this:Subassembly.EG_Surface="[new PreviewSurfaceTarget(&quot;EG_Surface&quot;, True, 1000, 3, -1000, 3)]"
{{Ns}}>
  <x:Members>
    <x:Property Name="Geometry" Type="InOutArgument(asw:Geometry)" />
    <x:Property Name="SubassemblyErrorCenter" Type="InOutArgument(asw:SubassemblyErrorCenter)" />
    <x:Property Name="SubassemblyRunMode" Type="InOutArgument(asw:SubassemblyRunMode)" />
    {{Member("Side", "InArgument(asw:EnumType)", null)}}
    {{Member("BottomHalfWidth", "InArgument(x:Double)", "Half of the bottom width on this side")}}
    {{Member("Slope1H", "InArgument(x:Double)", "First side slope 1:Slope1H")}}
    {{Member("BenchHeight", "InArgument(x:Double)", "Bench height above the bottom; 0 = no bench")}}
    {{Member("BenchWidth", "InArgument(x:Double)", "Bench width")}}
    {{Member("Slope2H", "InArgument(x:Double)", "Slope above the bench 1:Slope2H")}}
    {{liningMember}}
    {{Member("EG_Surface", "InArgument(asw:SurfaceTarget)", "Existing ground target surface")}}
  </x:Members>
  <sap:VirtualizedContainerService.HintSize>1188,809</sap:VirtualizedContainerService.HintSize>
  <mva:VisualBasic.Settings>Assembly references and imported namespaces serialized as XML namespaces</mva:VisualBasic.Settings>
  <Flowchart sap:VirtualizedContainerService.HintSize="1148,769" mva:VisualBasic.Settings="Assembly references and imported namespaces serialized as XML namespaces">
    <Flowchart.Variables>
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(41, &quot;AwayFromCrown&quot;)]" Modifiers="ReadOnly" Name="AwayFromCrown" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(1, &quot;Left&quot;)]" Modifiers="ReadOnly" Name="Left" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(20, &quot;LeftInsideLane&quot;)]" Modifiers="ReadOnly" Name="LeftInsideLane" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(21, &quot;LeftInsideShoulder&quot;)]" Modifiers="ReadOnly" Name="LeftInsideShoulder" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(22, &quot;LeftOutsideLane&quot;)]" Modifiers="ReadOnly" Name="LeftOutsideLane" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(23, &quot;LeftOutsideShoulder&quot;)]" Modifiers="ReadOnly" Name="LeftOutsideShoulder" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(11, &quot;No&quot;)]" Modifiers="ReadOnly" Name="No" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(-1, &quot;None&quot;)]" Modifiers="ReadOnly" Name="None" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(0, &quot;Right&quot;)]" Modifiers="ReadOnly" Name="Right" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(24, &quot;RightInsideLane&quot;)]" Modifiers="ReadOnly" Name="RightInsideLane" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(25, &quot;RightInsideShoulder&quot;)]" Modifiers="ReadOnly" Name="RightInsideShoulder" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(26, &quot;RightOutsideLane&quot;)]" Modifiers="ReadOnly" Name="RightOutsideLane" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(27, &quot;RightOutsideShoulder&quot;)]" Modifiers="ReadOnly" Name="RightOutsideShoulder" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(30, &quot;Supported&quot;)]" Modifiers="ReadOnly" Name="Supported" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(40, &quot;TowardsCrown&quot;)]" Modifiers="ReadOnly" Name="TowardsCrown" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(31, &quot;Unsupported&quot;)]" Modifiers="ReadOnly" Name="Unsupported" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(10, &quot;Yes&quot;)]" Modifiers="ReadOnly" Name="Yes" />
    </Flowchart.Variables>
    <Flowchart.StartNode>
      {{startNode}}
    </Flowchart.StartNode>
    {{refs}}
  </Flowchart>
</Activity>
""";
        }
    }
}
