using System.Globalization;
using System.Text;

namespace PktForge;

/// <summary>
/// Slope-from-top subassembly: the side slope starts where the offset target (TopLine, e.g. an offset alignment or a
/// design line) meets existing ground and runs down at 1:Slope1H to the baseline elevation (the design bottom profile).
/// It ends at the toe and leaves the bottom open: a stock MarkPoint on one toe plus a stock LinkToMarkedPoint on the
/// other closes the channel, so the bottom width follows the two design lines instead of a parameter.
/// Points: origin, mp-side (bottom elevation under the top line), daylight-side / controlpoint-side, toe-side.
/// Links: slope-side (+ Top, Datum, Slope, Cut).
/// </summary>
internal sealed record SlopeTopSpec
{
    public string Name { get; init; } = "SlopeTop";
    public double Slope1H { get; init; } = 3;
    public double MinHalfBottom { get; init; } = 0.5;
    public double PreviewTopOffset { get; init; } = 15;
    public string Units { get; init; } = "m";
    public string OutDir { get; init; } = ".";
    public string Description { get; init; } =
        "Slope from the top line: the side slope starts where the TopLine offset target meets existing ground (EG_Surface) and runs " +
        "down at 1:Slope1H to the baseline (design bottom) elevation, ending at the toe. Close the bottom with MarkPoint + LinkToMarkedPoint. " +
        "Point codes Origin/origin, mp-side, Daylight/daylight-side/controlpoint-side, Toe/Bottom/toe-side; link codes Top/Datum/Slope/Cut/slope-side. Generated by PktForge.";

    public const string Usage =
        """
        Slope-from-top subassembly (top line target -> slope down to the design bottom; bottom closed by LinkToMarkedPoint):
          PktForge slopetop [options]
          --name <name>              subassembly name (default SlopeTop); writes <name>_LEFT.pkt / <name>_RIGHT.pkt
          --slope1-h <n>             side slope 1:n (default 3)
          --min-half-bottom <m>      the toe never comes closer to the baseline than this (default 0.5)
          --preview-offset <m>       offset of the TopLine target in the Subassembly Composer preview (default 15)
          --units / --out / --desc   same as daylight
        """;

    public static SlopeTopSpec Parse(string[] args)
    {
        var spec = new SlopeTopSpec();
        for (int i = 1; i < args.Length; i += 2)
        {
            string key = args[i];
            if (i + 1 >= args.Length) throw new ArgumentException(key + " is missing a value");
            string val = args[i + 1];
            spec = key switch
            {
                "--name" => spec with { Name = val },
                "--slope1-h" => spec with { Slope1H = Num(key, val) },
                "--min-half-bottom" => spec with { MinHalfBottom = Num(key, val) },
                "--preview-offset" => spec with { PreviewTopOffset = Num(key, val) },
                "--units" => spec with { Units = val },
                "--out" => spec with { OutDir = val },
                "--desc" => spec with { Description = val },
                _ => throw new ArgumentException("Unknown option: " + key)
            };
        }
        if (spec.Slope1H <= 0) throw new ArgumentException("slope1-h must be positive");
        if (spec.MinHalfBottom < 0 || spec.PreviewTopOffset <= 0) throw new ArgumentException("min-half-bottom must not be negative and preview-offset must be positive");
        return spec;
    }

    private static double Num(string key, string val)
    {
        if (!double.TryParse(val, NumberStyles.Float, CultureInfo.InvariantCulture, out double d))
            throw new ArgumentException(key + " is not a number: " + val);
        return d;
    }
}

internal static class SlopeTopWriter
{
    public static string Write(SlopeTopSpec spec, bool isLeft)
    {
        string side = isLeft ? "Left" : "Right";
        string toolName = PktWriter.SanitizeIdentifier(spec.Name) + "_" + side;
        string guid = Guid.NewGuid().ToString("N");
        int sideVal = isLeft ? 1 : 0;
        string n(double d) => PktWriter.N(d);

        var ps = new StringBuilder();
        ps.Append($"            <Side DataType=\"long\" TypeInfo=\"16\" DisplayName=\"Side\" Description=\"Side\">{sideVal}<Enum><Left DisplayName=\"Left\">1</Left><Right DisplayName=\"Right\">0</Right></Enum></Side>\n");
        ps.Append($"            <Slope1H DataType=\"double\" TypeInfo=\"16\" DisplayName=\"Slope1H\" Description=\"Side slope 1:Slope1H (horizontal per 1 vertical)\">{n(spec.Slope1H)}</Slope1H>\n");
        ps.Append($"            <MinHalfBottom DataType=\"double\" TypeInfo=\"16\" DisplayName=\"MinHalfBottom\" Description=\"The toe never comes closer to the baseline than this\">{n(spec.MinHalfBottom)}</MinHalfBottom>");

        string outPath = Path.Combine(spec.OutDir, spec.Name + "_" + side.ToUpperInvariant() + ".pkt");
        PktWriter.WritePackage(outPath, guid,
            SlopeTopXaml.Build(spec, isLeft),
            PktWriter.BuildAtcXml(toolName, PktWriter.XmlEscape(spec.Description), guid, ps.ToString(), spec.Units));
        return outPath;
    }
}

/// <summary>
/// WF4 flowchart: P1 origin (baseline = design bottom), P2 under the TopLine target at bottom elevation (mp-side),
/// AP1 ground above P2; D1 [ground above the bottom] -> P3 daylight (top of slope on the ground), P4 toe on the
/// bottom elevation, L1 slope link; else nothing (no cut on this side).
/// </summary>
internal static class SlopeTopXaml
{
    const string Ns = """
         xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities"
         xmlns:asa="clr-namespace:Autodesk.SubassemblyComposer.API;assembly=Subassembly.API"
         xmlns:asa1="clr-namespace:Autodesk.SubassemblyComposer.API;assembly=Subassembly.WorkflowEngine"
         xmlns:asa2="clr-namespace:Autodesk.SubassemblyComposer.ActivityLibrary;assembly=Subassembly.ActivityLibrary"
         xmlns:asw="clr-namespace:Autodesk.SubassemblyComposer.WorkflowEngine;assembly=Subassembly.WorkflowEngine"
         xmlns:av="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
         xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
         xmlns:mva="clr-namespace:Microsoft.VisualBasic.Activities;assembly=System.Activities"
         xmlns:s="clr-namespace:System;assembly=mscorlib"
         xmlns:s1="clr-namespace:System;assembly=System.Core"
         xmlns:s2="clr-namespace:System;assembly=System"
         xmlns:s3="clr-namespace:System;assembly=System.Runtime.WindowsRuntime"
         xmlns:sa="clr-namespace:System.Activities;assembly=System.Activities"
         xmlns:sads="http://schemas.microsoft.com/netfx/2010/xaml/activities/debugger"
         xmlns:sap="http://schemas.microsoft.com/netfx/2009/xaml/activities/presentation"
         xmlns:scg="clr-namespace:System.Collections.Generic;assembly=mscorlib"
         xmlns:this="clr-namespace:"
         xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        """;

    const string Common = "Geometry=\"[Geometry]\" ShowErrors=\"True\" SubassemblyErrorCenter=\"[SubassemblyErrorCenter]\" SubassemblyRunMode=\"[SubassemblyRunMode]\"";

    static int _activity;
    static readonly List<string> _refs = new();

    static string Codes(string owner, string kind, IEnumerable<string> codes)
    {
        var sb = new StringBuilder();
        sb.Append($"<{owner}.{kind}><scg:List x:TypeArguments=\"InArgument(x:String)\" Capacity=\"4\">");
        foreach (string c in codes) sb.Append($"<InArgument x:TypeArguments=\"x:String\">{c}</InArgument>");
        sb.Append($"</scg:List></{owner}.{kind}>");
        return sb.ToString();
    }

    static string PointXY(string id, string title, string from, string dx, string dy, params string[] codes)
    {
        int aid = ++_activity;
        string fromAttr = from == null ? "FromPoint=\"{x:Null}\"" : $"FromPoint=\"{from}\"";
        return $"<asa2:CreatePoint AutoLinkCodes=\"{{x:Null}}\" AutoLinkGeometryName=\"{{x:Null}}\" {fromAttr} ActivityId=\"{aid}\" ApplyAOR=\"False\" AutoLink=\"False\" DisplayName=\"{id} {title}\" {Common} PointNumber=\"{id}\" Positioning=\"DeltaXAndDeltaY\" Side=\"[Side]\">"
             + $"<asa2:CreatePoint.Arguments><InArgument x:TypeArguments=\"x:Double\" x:Key=\"DeltaX1\">{dx}</InArgument><InArgument x:TypeArguments=\"x:Double\" x:Key=\"DeltaY1\">{dy}</InArgument></asa2:CreatePoint.Arguments>"
             + Codes("asa2:CreatePoint", "PointCodes", codes) + "</asa2:CreatePoint>";
    }

    /// <summary>Point at the offset target (same elevation as the reference point), the Subassembly Composer "Angle and Delta X" positioning with an offset target.</summary>
    static string PointAtOffsetTarget(string id, string title, string from, string targetName, params string[] codes)
    {
        int aid = ++_activity;
        return $"<asa2:CreatePoint AutoLinkCodes=\"{{x:Null}}\" AutoLinkGeometryName=\"{{x:Null}}\" ActivityId=\"{aid}\" ApplyAOR=\"False\" AutoLink=\"False\" DisplayName=\"{id} {title}\" FromPoint=\"{from}\" {Common} PointNumber=\"{id}\" Positioning=\"AngleAndDeltaX\" Side=\"[Side]\">"
             + "<asa2:CreatePoint.Arguments>"
             + "<InArgument x:TypeArguments=\"x:String\" x:Key=\"AngleReferencePoint6\">None</InArgument>"
             + "<InArgument x:TypeArguments=\"x:Boolean\" x:Key=\"ReverseAngleReference6\">False</InArgument>"
             + "<InArgument x:TypeArguments=\"x:Double\" x:Key=\"Angle6\">0</InArgument>"
             + "<InArgument x:TypeArguments=\"x:Double\" x:Key=\"DeltaX6\">0</InArgument>"
             + $"<InArgument x:TypeArguments=\"asw:OffsetTarget\" x:Key=\"OffsetTarget6\">[{targetName}]</InArgument>"
             + "</asa2:CreatePoint.Arguments>"
             + Codes("asa2:CreatePoint", "PointCodes", codes) + "</asa2:CreatePoint>";
    }

    static string AuxOnSurface(string id, string title, string from, string dxExpr)
    {
        int aid = ++_activity;
        return $"<asa2:CreateAuxPoint AutoLinkCodes=\"{{x:Null}}\" AutoLinkGeometryName=\"{{x:Null}}\" PointCodes=\"{{x:Null}}\" ActivityId=\"{aid}\" ApplyAOR=\"False\" AutoLink=\"False\" DisplayName=\"{id} {title}\" FromPoint=\"{from}\" {Common} PointNumber=\"{id}\" Positioning=\"DeltaXOnSurface\" Side=\"[Side]\">"
             + "<asa2:CreateAuxPoint.Arguments>"
             + $"<InArgument x:TypeArguments=\"x:Double\" x:Key=\"DeltaX4\">{dxExpr}</InArgument>"
             + "<InArgument x:TypeArguments=\"asw:SurfaceTarget\" x:Key=\"SurfaceTarget4\">[EG_Surface]</InArgument>"
             + "<x:Null x:Key=\"OffsetTarget4\" />"
             + "<InArgument x:TypeArguments=\"x:Double\" x:Key=\"DeltaYForLayout4\">3</InArgument>"
             + "</asa2:CreateAuxPoint.Arguments></asa2:CreateAuxPoint>";
    }

    static string Link(string id, string title, string start, string end, params string[] codes)
    {
        int aid = ++_activity;
        return $"<asa2:CreateLink ActivityId=\"{aid}\" ApplyAOR=\"False\" DisplayName=\"{id} {title}\" EndPoint=\"{end}\" {Common} IsEnabled=\"True\" LinkNumber=\"{id}\" StartPoint=\"{start}\">"
             + Codes("asa2:CreateLink", "LinkCodes", codes) + "</asa2:CreateLink>";
    }

    static string Step(string name, string sequenceTitle, IEnumerable<string> activities, string next)
    {
        _refs.Add(name);
        var sb = new StringBuilder();
        sb.Append($"<FlowStep x:Name=\"{name}\"><Sequence DisplayName=\"{sequenceTitle}\">");
        foreach (string a in activities) sb.Append(a);
        sb.Append("</Sequence>");
        if (next != null) sb.Append("<FlowStep.Next>").Append(next).Append("</FlowStep.Next>");
        sb.Append("</FlowStep>");
        return sb.ToString();
    }

    static string Decision(string name, string title, string condition, string whenTrue, string whenFalse)
    {
        _refs.Add(name);
        var sb = new StringBuilder();
        sb.Append($"<FlowDecision x:Name=\"{name}\" Condition=\"{condition}\" DisplayName=\"{title}\">");
        if (whenTrue != null) sb.Append("<FlowDecision.True>").Append(whenTrue).Append("</FlowDecision.True>");
        if (whenFalse != null) sb.Append("<FlowDecision.False>").Append(whenFalse).Append("</FlowDecision.False>");
        sb.Append("</FlowDecision>");
        return sb.ToString();
    }

    static string Member(string name, string type, string description)
    {
        string desc = description == null ? "" : $"<asw:Description2Attribute Description=\"{description}\" />";
        return $"<x:Property Name=\"{name}\" Type=\"{type}\"><x:Property.Attributes><asw:EnabledFlag2Attribute EnabledFlag=\"True\" />{desc}</x:Property.Attributes></x:Property>";
    }

    public static string Build(SlopeTopSpec spec, bool isLeft)
    {
        lock (_refs)
        {
            _activity = 0;
            _refs.Clear();
            int sideVal = isLeft ? 1 : 0;
            string sideName = isLeft ? "Left" : "Right";
            string side = isLeft ? "left" : "right";
            string n(double d) => PktWriter.N(d);
            double previewOffset = isLeft ? -spec.PreviewTopOffset : spec.PreviewTopOffset;

            // ground above the bottom: slope from the top line down to the toe
            string branchCut = Step("__Cut", "Slope down to the toe",
                new[]
                {
                    PointXY("P3", "Daylight (top of slope)", "P2", "0", "[Math.Max(AP1.Y - P2.Y, 0)]", "Daylight", "Daylight_Cut", "daylight-" + side, "controlpoint-" + side),
                    PointXY("P4", "Toe", "P1", "[Math.Max(P3.X - (P3.Y - P1.Y) * Slope1H, MinHalfBottom)]", "0", "Toe", "Bottom", "toe-" + side),
                    Link("L1", "Side slope", "P3", "P4", "Top", "Datum", "Slope", "Cut", "slope-" + side)
                }, null);
            string d1 = Decision("__D1", "Ground above the bottom?", "[AP1.Y &gt; P1.Y]", branchCut, null);

            var start = new List<string>
            {
                PointXY("P1", "Origin", null, "0", "0", "Origin", "origin"),
                PointAtOffsetTarget("P2", "Under the top line", "P1", "TopLine", "MP", "mp-" + side),
                AuxOnSurface("AP1", "Ground above the top line", "P2", "0")
            };
            string startNode = Step("__Start", "Top line", start, d1);

            var refs = new StringBuilder();
            foreach (string r in _refs) refs.Append($"<x:Reference>{r}</x:Reference>");

            return
$$"""
<Activity mc:Ignorable="sads sap" x:Class="Subassembly" this:Subassembly.Side="[new EnumType({{sideVal}}, &quot;{{sideName}}&quot;, &quot;Side&quot;)]" this:Subassembly.Slope1H="{{n(spec.Slope1H)}}" this:Subassembly.MinHalfBottom="{{n(spec.MinHalfBottom)}}" this:Subassembly.EG_Surface="[new PreviewSurfaceTarget(&quot;EG_Surface&quot;, True, 1000, 3, -1000, 3)]" this:Subassembly.TopLine="[new PreviewOffsetTarget(&quot;TopLine&quot;, True, {{n(previewOffset)}})]"
{{Ns}}>
  <x:Members>
    <x:Property Name="Geometry" Type="InOutArgument(asw:Geometry)" />
    <x:Property Name="SubassemblyErrorCenter" Type="InOutArgument(asw:SubassemblyErrorCenter)" />
    <x:Property Name="SubassemblyRunMode" Type="InOutArgument(asw:SubassemblyRunMode)" />
    {{Member("Side", "InArgument(asw:EnumType)", null)}}
    {{Member("Slope1H", "InArgument(x:Double)", "Side slope 1:Slope1H")}}
    {{Member("MinHalfBottom", "InArgument(x:Double)", "The toe never comes closer to the baseline than this")}}
    {{Member("EG_Surface", "InArgument(asw:SurfaceTarget)", "Existing ground target surface")}}
    {{Member("TopLine", "InArgument(asw:OffsetTarget)", "Top line of the slope (offset target: alignment, feature line or polyline)")}}
  </x:Members>
  <sap:VirtualizedContainerService.HintSize>1188,809</sap:VirtualizedContainerService.HintSize>
  <mva:VisualBasic.Settings>Assembly references and imported namespaces serialized as XML namespaces</mva:VisualBasic.Settings>
  <Flowchart sap:VirtualizedContainerService.HintSize="1148,769" mva:VisualBasic.Settings="Assembly references and imported namespaces serialized as XML namespaces">
    <Flowchart.Variables>
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(41, &quot;AwayFromCrown&quot;)]" Modifiers="ReadOnly" Name="AwayFromCrown" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(1, &quot;Left&quot;)]" Modifiers="ReadOnly" Name="Left" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(20, &quot;LeftInsideLane&quot;)]" Modifiers="ReadOnly" Name="LeftInsideLane" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(21, &quot;LeftInsideShoulder&quot;)]" Modifiers="ReadOnly" Name="LeftInsideShoulder" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(22, &quot;LeftOutsideLane&quot;)]" Modifiers="ReadOnly" Name="LeftOutsideLane" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(23, &quot;LeftOutsideShoulder&quot;)]" Modifiers="ReadOnly" Name="LeftOutsideShoulder" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(11, &quot;No&quot;)]" Modifiers="ReadOnly" Name="No" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(-1, &quot;None&quot;)]" Modifiers="ReadOnly" Name="None" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(0, &quot;Right&quot;)]" Modifiers="ReadOnly" Name="Right" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(24, &quot;RightInsideLane&quot;)]" Modifiers="ReadOnly" Name="RightInsideLane" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(25, &quot;RightInsideShoulder&quot;)]" Modifiers="ReadOnly" Name="RightInsideShoulder" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(26, &quot;RightOutsideLane&quot;)]" Modifiers="ReadOnly" Name="RightOutsideLane" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(27, &quot;RightOutsideShoulder&quot;)]" Modifiers="ReadOnly" Name="RightOutsideShoulder" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(30, &quot;Supported&quot;)]" Modifiers="ReadOnly" Name="Supported" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(40, &quot;TowardsCrown&quot;)]" Modifiers="ReadOnly" Name="TowardsCrown" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(31, &quot;Unsupported&quot;)]" Modifiers="ReadOnly" Name="Unsupported" />
      <Variable x:TypeArguments="asw:EnumType" Default="[new EnumType(10, &quot;Yes&quot;)]" Modifiers="ReadOnly" Name="Yes" />
    </Flowchart.Variables>
    <Flowchart.StartNode>
      {{startNode}}
    </Flowchart.StartNode>
    {{refs}}
  </Flowchart>
</Activity>
""";
        }
    }
}
